### PR TITLE
Add fallback to SMBus2, add is_connected() method to microdotphat and NanoMatrix 

### PR DESCRIPTION
**Pull request by Bertware**
This PR adds a fallback to SMBus2, as well as a new is_connected() method.

is_connected() checks if the microdotphat is connected by trying to write a byte to it. It is useful for projects where you want to enable/disable output to the display based on the presence of the module, or if you just want to test the wiring of your project. I believe it is a good addition to the library. Let me know if you do not believe it fits the library, or if you'd like to see changes to the proposed code.

Regards,
Bert

### CODE REVIEW

**Comment by Gadgetoid** [comment]
Thank you -

I don't think you need `as e` when not doing anything with the caught exception- I might be wrong though!

Also, while you're digging about in the plumbing it might be a good idea to change `exit` to `raise RuntimeError` because hard exits do *weird* things in libraries sometimes and are horribly unpythonic (yes my fault, from old bad habits).

Looks like you're being thorough! I really appreciate you taking the time to look over these libraries and suggest changes- most of the time I'm the only person peering under the hood and... well as you can clearly see in some cases it really shows. Having someone else critique my sometimes awful code is really helpful.

As with https://github.com/pimoroni/scroll-phat-hd/pull/67 I do wonder if we should just roll with `smbus2` since it appears to have been sufficiently battle tested and in widespread use.

**Comment by Bertware** [comment]
I copied over the whole smbus import from the scrollphathd library, adjusted them now for SMBus2 and exceptions. Glad to hear you like the PR's, in that case I'll keep contributing my local changes back :) 

I only tested with the project I'm working on now, so you might want to grab a pi and test with some of the graphic examples (I'm only using text features ATM). 

Since Python2 is EOL for almost a year, and Python 3.5 is EOL as well, do you mind if I remove some Python-2 specific stuff? (I'm not going to go on a clean-up spree, but might encounter some while working on other things, such as the SMBus installation instructions now, pip vs pip3, etc)

**Comment by Gadgetoid** [comment]
Right now I'm still trying to keep Python 2 compatibility for better or worse... but maybe it's time to start phasing it out. Python 2.x holdouts should still be able to use the older library version if all else fails.

My main worry is that it will unearth some group of holdout customers, still desperately clinging to the Python 2.7 bygone past, refusing to give it up, and the resulting tech support issues will be confusing.

I'd *love* to get shot of 2.x though and wonder if I can head off support issues at the pass with some kind of big obvious warning.

I guess... tldr: assume Python 2.x can be dropped and I'll deal with issues as they arise.

**Comment by Bertware** [comment]
Should I change something for this to get merged?

**Comment by Gadgetoid** [comment]
> Should I change something for this to get merged?

I don't think so. Sorry it takes me forever to get 'round to things- I'm swamped!

**Comment by Gadgetoid** [comment]
Looks like `smbus2` needs to be added as a dependency:

```patch
diff --git a/library/setup.py b/library/setup.py
index 783ac44..79572b1 100644
--- a/library/setup.py
+++ b/library/setup.py
@@ -51,5 +51,5 @@ setup(
     py_modules      = [],
     packages        = ['microdotphat'],
     include_package_data = True,
-    install_requires= [ 'numpy' ]
+    install_requires= [ 'numpy', 'smbus2' ]
 )
 ```

**Pull request merged**
